AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - Guardfile
    - vendor/**/*
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*_spec.rb

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false
